// Export pages
export '/pages/home_page/home_page_widget.dart' show HomePageWidget;
export '/plataforma/plataforma_widget.dart' show PlataformaWidget;
export '/apppro/apppro_widget.dart' show AppproWidget;
export '/bacbo/bacbo_widget.dart' show BacboWidget;
export '/football/football_widget.dart' show FootballWidget;
export '/dragon_tiger/dragon_tiger_widget.dart' show DragonTigerWidget;
export '/mines/mines_widget.dart' show MinesWidget;
export '/extreme/extreme_widget.dart' show ExtremeWidget;
export '/penalty/penalty_widget.dart' show PenaltyWidget;
export '/fortunetiger/fortunetiger_widget.dart' show FortunetigerWidget;
export '/oxfortune/oxfortune_widget.dart' show OxfortuneWidget;
export '/mousefortune/mousefortune_widget.dart' show MousefortuneWidget;
export '/balloon/balloon_widget.dart' show BalloonWidget;
export '/plinko/plinko_widget.dart' show PlinkoWidget;
export '/aviator/aviator_widget.dart' show AviatorWidget;
export '/login/login_widget.dart' show LoginWidget;
export '/cadastro/cadastro_widget.dart' show CadastroWidget;
export '/notificacao/notificacao_widget.dart' show NotificacaoWidget;
